### ISSUE TITLE
'gradle build' doesn't include worldlists in jar

### ISSUE THREAD

**Issue by apbryan** [c-a-m/passfault#43]
cloning this repository and running `gradle build` followed by `java -jar core/build/libs/passfault-core-0.8-SNAPSHOT.jar` yields:

`Exception in thread "main" java.io.IOException: could not load resource /org/owasp/passfault/wordlists/words.properties
	at org.owasp.passfault.FinderByPropsBuilder$SystemResourceReader.loadResource(FinderByPropsBuilder.java:231)
	at org.owasp.passfault.FinderByPropsBuilder.build(FinderByPropsBuilder.java:97)
	at org.owasp.passfault.TextAnalysis.<init>(TextAnalysis.java:49)
	at org.owasp.passfault.TextAnalysis.main(TextAnalysis.java:42)`

**Comment by c-a-m** [comment]
Sorry for not seeing this issue earlier.  I just updated my email settings.  I'll get looking at it.

**Comment by c-a-m** [comment]
I updated the build instructions to use the gradlew wrapper.  @apbryan would you mind trying this again to see if everything builds for you?

**Comment by c-a-m** [comment]
So the wordlist.jar is a dependency of the passfault-core jar in this newer build.  I'm not sure if we want to keep it that way or not.  Regardless we should update the documentation on how to run it. 

I tried using gradle run, but apparently there is a bug regarding it: https://issues.gradle.org/browse/GRADLE-2310  That prevents us from reading from the console or System.in

**Comment by bernardoaraujor** [comment]
I'm having a similar issue.
I'm trying to import the project into IntelliJ+Gradle.

When Gradle tries to build it, I get the following message:

Expected configuration ':jsonService:wordlists' to contain exactly one file, however, it contains no files.  Consult IDE log for more details (Help | Show Log)

**Comment by bernardoaraujor** [comment]
same thing with command line:

bernardo@bernardo-UX51VZA:~/Documents/MestradoCripto/passfault/passfaultJava$ ./gradlew installDist

FAILURE: Build failed with an exception.

* Where:
Build file '/home/bernardo/Documents/MestradoCripto/passfault/passfaultJava/jsonService/build.gradle' line: 20

* What went wrong:
A problem occurred evaluating project ':jsonService'.
> Expected configuration ':jsonService:wordlists' to contain exactly one file, however, it contains no files.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 4.886 secs

**Comment by bernardoaraujor** [comment]
worked after i deleted appEngine and jsonService directories
